# AWS Bedrock + LiteLLM Testing

Simple tests for Bedrock models via LiteLLM with cost tracking.

In [3]:
import os

from dotenv import load_dotenv
from litellm import completion, completion_cost

load_dotenv()
print("✓ Loaded")

✓ Loaded

In [4]:
# Config
region = os.getenv("AWS_REGION")
token = os.getenv("AWS_BEARER_TOKEN_BEDROCK")
llama_1b = os.getenv("BEDROCK_LLAMA_1B")
llama_3b = os.getenv("BEDROCK_LLAMA_3B")
llama_8b = os.getenv("BEDROCK_LLAMA_8B")
gpt_oss_20b = os.getenv("BEDROCK_GPT_OSS_20B")
gpt_oss_120b = os.getenv("BEDROCK_GPT_OSS_120B")

print(f"Region: {region}")
print(f"Token: {'✓' if token else '✗'}")
print(f"Llama Models: {llama_1b}, {llama_3b}, {llama_8b}")
print(f"GPT OSS Models: {gpt_oss_20b}, {gpt_oss_120b}")

Region: us-east-1
Token: ✓
Llama Models: us.meta.llama3-2-1b-instruct-v1:0, us.meta.llama3-2-3b-instruct-v1:0, us.meta.llama3-1-8b-instruct-v1:0
GPT OSS Models: openai.gpt-oss-20b-1:0, openai.gpt-oss-120b-1:0

## Test 1: Basic Call

In [5]:
response = completion(
    model=f"bedrock/{llama_1b}",
    messages=[{"role": "user", "content": "Say hello in 5 words"}],
    max_tokens=50,
    temperature=0,
)

print(f"Response: {response.choices[0].message.content}")
print(f"Tokens: {response.usage.total_tokens}")
print(f"Cost: ${completion_cost(completion_response=response):.6f}")

Response: Hello, it's nice to meet you.
Tokens: 51
Cost: $0.000005

## Test 1b: GPT OSS 120B

In [6]:
response = completion(
    model=f"bedrock/{gpt_oss_120b}",
    messages=[{"role": "user", "content": "Say hello in 5 words"}],
    max_tokens=200,
    temperature=0,
)

print(f"Response: {response.choices[0].message.content}")
print(f"Tokens: {response.usage.total_tokens}")
print(f"Cost: ${completion_cost(completion_response=response):.6f}")

Response: Hello dear friend, great day.
Tokens: 239
Cost: $0.000111

## Test 2: Math Reasoning

In [7]:
response = completion(
    model=f"bedrock/{llama_8b}",
    messages=[
        {"role": "system", "content": "Think step by step"},
        {
            "role": "user",
            "content": "If I have 3 apples and buy 2 more, then give 1 away, how many?",
        },
    ],
    max_tokens=150,
    temperature=0,
)

print(response.choices[0].message.content)
print(f"\nTokens: {response.usage.total_tokens}")
print(f"Cost: ${completion_cost(completion_response=response):.6f}")

Let's break it down step by step:

1. You start with 3 apples.
2. You buy 2 more apples, so now you have 3 + 2 = 5 apples.
3. You give 1 apple away, so now you have 5 - 1 = 4 apples.

So, you have 4 apples.

Tokens: 114
Cost: $0.000025

## Test 3: Compare All Models

In [8]:
question = "What is 2+2?"
total_cost = 0

for name, model in [("1B", llama_1b), ("3B", llama_3b), ("8B", llama_8b)]:
    response = completion(
        model=f"bedrock/{model}",
        messages=[{"role": "user", "content": question}],
        max_tokens=20,
        temperature=0,
    )

    cost = completion_cost(completion_response=response)
    total_cost += cost

    print(f"{name}: {response.choices[0].message.content}")
    print(f"     Tokens: {response.usage.total_tokens}, Cost: ${cost:.6f}\n")

print(f"Total: ${total_cost:.6f}")

1B: 2 + 2 = 4.
     Tokens: 51, Cost: $0.000005

3B: 2 + 2 = 4
     Tokens: 50, Cost: $0.000007

8B:

2 + 2 = 4
     Tokens: 31, Cost: $0.000007

Total: $0.000019

## Test 5: Temperature Effects

In [9]:
prompt = "The future of AI is"

for temp in [0.0, 0.7, 1.0]:
    response = completion(
        model=f"bedrock/{llama_3b}",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=30,
        temperature=temp,
    )

    print(f"Temp {temp}: {response.choices[0].message.content}\n")

Temp 0.0: The future of AI is a topic of much debate and speculation. Here are some potential trends and developments that could shape the future of AI:

1.

Temp 0.7: The future of AI is a complex and multifaceted topic, with various predictions and possibilities. Here are some potential directions that AI may take in the

Temp 1.0: The future of AI is likely to be shaped by advancements in several areas, including:

1. **Increased Integration with Other Technologies**: AI will continue to

## Test 6: DSPy with LiteLLM

In [16]:
import dspy
from dspy import LM

# Configure DSPy to use LiteLLM with Bedrock
lm = LM(model=f"bedrock/{llama_8b}", temperature=0, max_tokens=100)
dspy.configure(lm=lm)


# Define a simple signature
class BasicQA(dspy.Signature):
    """Answer questions concisely."""

    question: str = dspy.InputField()
    answer: str = dspy.OutputField()


# Create and test predictor
qa = dspy.ChainOfThought(BasicQA)
question = "What is the capital of France?"
response = qa(question=question)

print(f"Question: {question}")
print(f"Answer: {response.answer}")

# Inspect available fields
print(f"\nAvailable fields: {list(response.keys())}")

# Try to access reasoning if available
if hasattr(response, "reasoning"):
    print(f"\nReasoning: {response.reasoning}")
elif "reasoning" in response:
    print(f"\nReasoning: {response.reasoning}")

Question: What is the capital of France?
Answer: Paris

Available fields: ['reasoning', 'answer']

Reasoning: The capital of France is a well-known fact that can be easily looked up in a world atlas or a reliable online source. It is a widely accepted piece of information that is commonly taught in schools and is a basic fact that many people know.

In [17]:
# Access DSPy call history for cost tracking
from litellm import completion_cost

# Get the last call from DSPy's history
last_call = lm.history[-1]

print("DSPy Call History:")
print(f"  Prompt tokens: {last_call['usage']['prompt_tokens']}")
print(f"  Completion tokens: {last_call['usage']['completion_tokens']}")
print(f"  Total tokens: {last_call['usage']['total_tokens']}")

# Calculate cost from the response
if "response" in last_call:
    cost = completion_cost(completion_response=last_call["response"])
    print(f"  Cost: ${cost:.6f}")
else:
    print("\n  Note: Raw response not available in history")
    print("  You can enable this with: lm = LM(..., cache=False)")

DSPy Call History:
  Prompt tokens: 169
  Completion tokens: 68
  Total tokens: 237
  Cost: $0.000052

# GEPA/DSPy HotpotQA Task

Testing prompt optimization on multi-hop question answering.

In [53]:
import dspy
from datasets import load_dataset


def init_dataset(num_samples=100):
    # Load HotpotQA dataset
    raw_data = load_dataset("hotpot_qa", "fullwiki")

    # Process train split
    raw_train = (
        raw_data["train"].shuffle(seed=42).select(range(min(len(raw_data["train"]), num_samples)))
    )
    train_split = [
        dspy.Example(
            {
                "question": x["question"],
                "answer": x["answer"],
            }
        ).with_inputs("question")
        for x in raw_train
    ]

    # Process validation split for test
    raw_val = (
        raw_data["validation"]
        .shuffle(seed=42)
        .select(range(min(len(raw_data["validation"]), num_samples)))
    )
    test_split = [
        dspy.Example(
            {
                "question": x["question"],
                "answer": x["answer"],
            }
        ).with_inputs("question")
        for x in raw_val
    ]

    # Split train into train/val
    tot_num = len(train_split)
    train_set = train_split[: int(0.5 * tot_num)]
    val_set = train_split[int(0.5 * tot_num) :]
    test_set = test_split

    return train_set, val_set, test_set


train_set, val_set, test_set = init_dataset(num_samples=100)
print(f"Train: {len(train_set)}, Val: {len(val_set)}, Test: {len(test_set)}")
print(f"Example: {train_set[0]}")

Train: 50, Val: 50, Test: 100
Example: Example({'question': 'Which airport is located in Maine, Sacramento International Airport or Knox County Regional Airport?', 'answer': 'Knox County Regional Airport'}) (input_keys={'question'})

In [62]:
from dspy import LM

# Configure DSPy to use LiteLLM with Bedrock (task agent)
lm = LM(model=f"bedrock/{gpt_oss_20b}", temperature=0.7, max_tokens=8192)
dspy.configure(lm=lm)

In [63]:
class GenerateResponse(dspy.Signature):
    """Answer the question with a short, factual response."""

    question = dspy.InputField()
    answer = dspy.OutputField(desc="A short factual answer (1-5 words)")


program = dspy.ChainOfThought(GenerateResponse)


def normalize_answer(s):
    """Normalize answer for comparison."""
    if s is None:
        return ""
    return s.lower().strip()


def metric(example, prediction, trace=None, pred_name=None, pred_trace=None):
    gold = normalize_answer(example["answer"])
    pred = normalize_answer(prediction.answer)
    if not pred:
        return 0
    # Exact match or gold contained in prediction
    return int(gold == pred or gold in pred or pred in gold)

In [64]:
import dspy

evaluate = dspy.Evaluate(
    devset=test_set, metric=metric, num_threads=32, display_table=True, display_progress=True
)

evaluate(program)

Average Metric: 27.00 / 86 (31.4%):  85%|████████▌ | 85/100 [00:25<00:03,  4.48it/s]

2026/02/11 12:05:42 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.

Average Metric: 27.00 / 95 (28.4%):  95%|█████████▌| 95/100 [00:30<00:03,  1.63it/s]

2026/02/11 12:05:47 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.

Average Metric: 27.00 / 100 (27.0%): 100%|██████████| 100/100 [00:42<00:00,  2.35it/s]

2026/02/11 12:05:59 INFO dspy.evaluate.evaluate: Average Metric: 27 / 100 (27.0%)

,question,example_answer,reasoning,pred_answer,metric
0,What nationality was Oliver Reed's character in the film Royal Flash?,Prussian,"In the 1975 film *Royal Flash*, Oliver Reed portrays the Prince of...",British,✔️ [0]
1,Pacific Mozart Ensemble performed which German composer's Der Lind...,Kurt Julian Weill,The Pacific Mozart Ensemble performed “Der Lindberghflug” in 2002....,Rolf Vogel,✔️ [0]
2,"Who released the song ""With or Without You"" first, Jai McDowall or...",U2,The song “With or Without You” is a hit single by the Irish rock b...,U2,✔️ [1]
3,"What Kentucky county has a population of 60,316 and features the L...",Oldham County,NaN,NaN,✔️ [0]
4,"Para Hills West, South Australia lies within a city with what esti...","138,535","Para Hills West is a suburb of Adelaide, the capital city of South...","Adelaide, about 1.3 million",✔️ [0]
...,...,...,...,...,...
95,"What company has a headquarters in Whitley, Convernty, United King...",Jaguar Land Rover,"The company headquartered in Whitley, Convernty, United Kingdom is...",Whitley,✔️ [0]
96,Who starred as an American attorney in Grey Gardens?,Ken Howard,Grey Gardens (2009) features a character known as the American att...,John M. G.,✔️ [0]
97,Was Princess Charlotte of Cambridge born before or after the repea...,after,The Royal Marriages Act 1772 was repealed by the Succession to the...,After,✔️ [1]
98,Hermann Wilhelm Göring was a veteran fighter pilot in a war that e...,1918,"Hermann Göring served as a fighter pilot during World War I, which...",1918,✔️ [1]
99,Ethel Winter worked with which avant-garde theater director?,Jean Erdman,Ethel Winter was a stage actress known for her collaborations with...,Paul S.,✔️ [0]

EvaluationResult(score=27.0, results=<list of 100 results>)

In [65]:
def metric_with_feedback(example, prediction, trace=None, pred_name=None, pred_trace=None):
    gold = normalize_answer(example["answer"])
    pred = normalize_answer(prediction.answer)

    # Handle None/empty answer
    if not pred:
        feedback_text = (
            "Your response was empty or could not be parsed. "
            "Please provide a short, factual answer to the question."
        )
        feedback_text += f" The correct answer is '{example['answer']}'."
        return dspy.Prediction(score=0, feedback=feedback_text)

    # Check for match
    score = int(gold == pred or gold in pred or pred in gold)

    if score == 1:
        feedback_text = f"Correct! The answer is '{example['answer']}'."
    else:
        feedback_text = f"Incorrect. You answered '{prediction.answer}', but the correct answer is '{example['answer']}'."
        feedback_text += " Make sure to provide a concise, factual answer."

    return dspy.Prediction(score=score, feedback=feedback_text)

In [66]:
from dspy import GEPA

optimizer = GEPA(
    metric=metric_with_feedback,
    auto="light",
    num_threads=64,
    track_stats=True,
    reflection_minibatch_size=3,
    # Using gpt_oss_120b for reflection - larger model for instruction generation
    reflection_lm=dspy.LM(model=f"bedrock/{gpt_oss_120b}", temperature=1.0, max_tokens=4096),
)

optimized_program = optimizer.compile(
    program,
    trainset=train_set,
    valset=val_set,
)

2026/02/11 12:06:39 INFO dspy.teleprompt.gepa.gepa: Running GEPA for approx 580 metric calls of the program. This amounts to 5.80 full evals on the train+val set.
2026/02/11 12:06:39 INFO dspy.teleprompt.gepa.gepa: Using 50 examples for tracking Pareto scores. You can consider using a smaller sample of the valset to allow GEPA to explore more diverse solutions within the same budget. GEPA requires you to provide the smallest valset that is just large enough to match your downstream task distribution, while providing as large trainset as possible.
GEPA Optimization:   0%|          | 0/580 [00:00<?, ?rollouts/s]2026/02/11 12:07:01 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:07:06 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:07:07 INFO dspy.evaluate.evaluate: Average Metric: 13.0 / 50 (26.0%)
2026/02/11 12:07:07 INFO dspy.teleprompt.gepa.gepa: Iteration 0: Base program full valset score: 0.26 over 50 / 50 examples
GEPA Optimization:   9%|▊         | 50/580 [00:28<04:59,  1.77rollouts/s]2026/02/11 12:07:07 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Selected program 0 score: 0.26

Average Metric: 1.00 / 3 (33.3%): 100%|██████████| 3/3 [00:30<00:00, 10.25s/it]

2026/02/11 12:07:38 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)

2026/02/11 12:07:44 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Proposed new text for predict: You are to answer trivia‑style questions with a **single, concise, factual response**. Follow these rules exactly:

1. **Output only the answer** – no explanation, no headings, no surrounding text, no markdown.
   - If the answer is a name, place, or occupation, output it exactly as the standard English term (e.g., `Astronomer`).
   - If the answer is a date, output it in the form **Month Day, Year** (e.g., `September 7, 1900`).
   - If the answer is a location comparison, output the name of the location that satisfies the query (e.g., `Woman's Viewpoint`).

2. **Answer must be factually correct**.
   - Use reliable knowledge sources (internal knowledge base, vetted external data, or well‑known reference works).
   - Do **not** guess or infer beyond the data you have; if you truly do not know, respond with `I don’t know`.

3. **Typical question types you will encounter**
   - **Geographical comparison** – e.g., “Which is farther west, X or Y?” → compare longitudes; output the location that is farther west.
   - **Occupational identification** – e.g., “X and Y have which mutual occupation?” → output the singular occupation (lower‑case may be acceptable, but match the style of the example).
   - **Birth‑date queries** – e.g., “When was [person/character] born?” → output the full birth date in the prescribed format.
   - **Any other factual attribute** – answer with the minimal exact phrase that satisfies the query.

4. **Avoid common pitfalls**
   - Do not include any reasoning, prefixes like “Answer:”, or trailing punctuation.
   - Ensure spelling, punctuation, and capitalization match the standard form of the answer (as shown in the examples).
   - Do not confuse similarly named entities; verify the correct one before answering.

5. **Examples**

   - Question: *Which is from farther west, Woman's Viewpoint or Al Jamila?* → `Woman's Viewpoint`
   - Question: *Al‑Battani and Ibn al‑Shatir have which mutual occupation?* → `Astronomer`
   - Question: *When was the delusional anarchist from the television film "The Revenge of Al Capone" born?* → `September 7, 1900`

Follow these instructions for every input you receive.
2026/02/11 12:07:52 INFO dspy.evaluate.evaluate: Average Metric: 2.0 / 3 (66.7%)
2026/02/11 12:07:52 INFO dspy.teleprompt.gepa.gepa: Iteration 1: New subsample score 2 is better than old score 1. Continue to full eval and add to candidate pool.
2026/02/11 12:08:17 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:08:23 INFO dspy.evaluate.evaluate: Average Metric: 17.0 / 50 (34.0%)
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Found a better program on the valset with score 0.34.
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Valset score for new program: 0.34 (coverage 50 / 50)
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Val aggregate for new program: 0.34
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Individual valset scores for new program: {0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 0, 16: 0, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 1: New valset pareto front scores: {0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 0, 16: 0, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Valset pareto front aggregate score: 0.34
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Updated valset pareto front programs: {0: {0, 1}, 1: {0, 1}, 2: {0, 1}, 3: {0, 1}, 4: {0, 1}, 5: {0, 1}, 6: {0, 1}, 7: {0, 1}, 8: {0, 1}, 9: {0, 1}, 10: {0, 1}, 11: {0, 1}, 12: {0, 1}, 13: {0, 1}, 14: {0, 1}, 15: {0, 1}, 16: {0, 1}, 17: {1}, 18: {1}, 19: {0, 1}, 20: {0, 1}, 21: {0, 1}, 22: {0, 1}, 23: {0, 1}, 24: {0, 1}, 25: {0, 1}, 26: {0, 1}, 27: {0, 1}, 28: {0, 1}, 29: {0, 1}, 30: {0, 1}, 31: {0, 1}, 32: {0, 1}, 33: {0, 1}, 34: {0, 1}, 35: {1}, 36: {0, 1}, 37: {0, 1}, 38: {0, 1}, 39: {0, 1}, 40: {1}, 41: {0, 1}, 42: {0, 1}, 43: {0, 1}, 44: {0, 1}, 45: {0, 1}, 46: {0, 1}, 47: {0, 1}, 48: {0, 1}, 49: {0, 1}}
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Best valset aggregate score so far: 0.34
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Best program as per aggregate score on valset: 1
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Best score on valset: 0.34
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 1: Linear pareto front program index: 1
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 1: New program candidate index: 1
GEPA Optimization:  18%|█▊        | 106/580 [01:44<08:21,  1.06s/rollouts]2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 2: No merge candidates found
2026/02/11 12:08:23 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Selected program 1 score: 0.34

Average Metric: 1.00 / 3 (33.3%): 100%|██████████| 3/3 [00:07<00:00,  2.52s/it]

2026/02/11 12:08:31 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)

2026/02/11 12:08:41 INFO dspy.teleprompt.gepa.gepa: Iteration 2: Proposed new text for predict: **Task Overview**
You will receive a single trivia‑style question. Your job is to return **only the exact answer**—nothing else (no explanations, headings, punctuation, or markdown). The answer must be a *single, concise, factually correct* phrase that directly satisfies the query.

---

### 1. General Output Rules

| Question type | Required answer format |
|---------------|------------------------|
| **Yes/No** (e.g., “Were X and Y from the same country?”) | `Yes` or `No` (capitalised, no period) |
| **Person’s occupation** (e.g., “X and Y have which mutual occupation?”) | Singular occupation in title case (e.g., `Astronomer`) |
| **Date** (birth, death, event) | `Month Day, Year` with a comma after the day (e.g., `September 7, 1900`). Use the full month name, a non‑breaking space before the day, and a normal space after the comma. |
| **Location name** (city, country, hill, building, etc.) | Exact standard English name (e.g., `Woman's Viewpoint`). Preserve apostrophes, hyphens, and capitalization. |
| **Geographical comparison** (farther west/east/north/south) | Output **only** the name of the location that satisfies the comparison, using the same rules as “Location name”. |
| **Specific event/thing name** (battle, treaty, book title, etc.) | Exact official title (e.g., `Second Battle of St Albans`). |
| **Unknown / not in reliable sources** | `I don’t know` |

**Never** add:
- “Answer:”, “The answer is”, or any introductory text.
- Periods, commas, or other trailing punctuation (except the mandatory comma in dates).
- Explanations, reasoning, or citations.

---

### 2. Accuracy Requirements

1. **Use reliable knowledge**: internal encyclopedic data, vetted external databases (e.g., Wikipedia, official biographies, scholarly references).
2. **Confirm the exact entity**: When a name could refer to multiple people/places, check distinguishing details (birthplace, profession, era) before answering.
3. **Cross‑check dates**: Ensure month, day, and year are correct; if two sources differ, prefer the most authoritative (e.g., official records, scholarly works).
4. **Geographical comparison**: Retrieve the longitude (or latitude for north/south) of each location and compare numerically.
5. **If any doubt remains after verification, output `I don’t know`.**

---

### 3. Step‑by‑Step Strategy (for internal use)

1. **Parse the question** – identify the required answer type (yes/no, date, occupation, location, comparison, etc.).
2. **Locate the entity/entities** – search the knowledge base for the exact person/place/event mentioned, paying attention to disambiguation notes.
3. **Extract the specific fact** based on the identified type.
   - *Date*: retrieve the full birth/death/event date.
   - *Occupation*: find the primary, widely‑accepted occupation (use the singular form).
   - *Comparison*: obtain decimal longitudes (west = more negative) or latitudes (north = larger) and decide which satisfies the query.
4. **Validate** the extracted fact against a second source when possible.
5. **Format** the answer exactly as required (see Table 1).
6. **Output** the answer alone.

---

### 4. Edge Cases & Common Pitfalls

- **Similar names**: `Robert Henry` could refer to many people; verify by role (e.g., successor of Ernest Davies as Bishop of St David’s).
- **Historical place names**: Use the modern English name that is standard in reference works (e.g., “Ukraine” for the region where Paul Celan was born).
- **Battles**: Use the *official* battle name, not a description (e.g., `Second Battle of St Albans`, not “the battle after Wakefield”).
- **Dates with different calendars**: Convert to the Gregorian calendar if the source uses Julian dates.
- **Capitalization**: Preserve the official capitalisation (e.g., `Al‑Battani`, `Woman's Viewpoint`).
- **Non‑English characters**: Transcribe to standard English spelling as found in reputable English‑language references.

---

### 5. Quick Reference Cheat‑Sheet

- **Yes/No** → `Yes` / `No`
- **Date** → `Month Day, Year` (e.g., `October 10, 1940`)
- **Occupation** → Title case, singular (e.g., `Astronomer`)
- **Location / Event / Battle** → Exact official name (preserve punctuation)
- **Comparison** → Name of the location that meets the condition
- **Unknown** → `I don’t know`

Follow these instructions for every input without deviation.
2026/02/11 12:08:47 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)
2026/02/11 12:08:47 INFO dspy.teleprompt.gepa.gepa: Iteration 2: New subsample score 1 is not better than old score 1, skipping
GEPA Optimization:  19%|█▉        | 112/580 [02:07<10:08,  1.30s/rollouts]2026/02/11 12:08:47 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Selected program 1 score: 0.34

Average Metric: 0.00 / 3 (0.0%): 100%|██████████| 3/3 [00:17<00:00,  5.93s/it]

2026/02/11 12:09:05 INFO dspy.evaluate.evaluate: Average Metric: 0.0 / 3 (0.0%)

2026/02/11 12:09:13 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Proposed new text for predict: **Task Overview**

You will receive a single trivia‑style question. Your job is to return **one short, exact answer** that satisfies the question, following the formatting rules below. Do **not** include any reasoning, explanations, headings, or markdown.

---

### 1. Answer Formatting Rules
| Question Type | Required Answer Format |
|---------------|------------------------|
| **Person’s name, place, organization, occupation, object, etc.** | Exact standard English term, with correct capitalization (e.g., `Astronomer`, `John Travolta`, `Rockville Pike`). |
| **Date** | `Month Day, Year` with a non‑breaking space between month and day and a comma after the day (e.g., `September 7, 1900`). |
| **Location comparison (“farther west/east/north/south”)** | Name of the location that satisfies the comparison (e.g., `Woman's Viewpoint`). |
| **When you truly have no reliable information** | `I don’t know` (exactly, capital “I”, lower‑case “don’t”, lower‑case “know”). |
| **Any other factual attribute** | The minimal exact phrase that fulfills the request (e.g., `Mars`, `42`). |

- **No punctuation** after the answer unless it is part of the required format (e.g., the comma in a date).
- **No surrounding text** such as “Answer:”, “The answer is”, or quotation marks.

---

### 2. How to Determine the Correct Answer
1. **Parse the question** to identify the main entity/entities and the attribute being asked for (e.g., spouse, road, town, occupation, birth date, comparative direction).
2. **Classify the question** into one of the supported types listed in the table above.
3. **Locate reliable data**:
   - Prefer well‑known reference works (e.g., Wikipedia, Encyclopædia Britannica, official government or organizational websites).
   - If you have internal knowledge that matches a reputable source, you may use it, but **verify** the fact against at least one external, authoritative source before answering.
   - For ambiguous names, first disambiguate by checking distinguishing details (occupation, birth year, notable works) to ensure you pick the correct individual.
4. **Special handling for specific types**
   - **Spouse / marital partner**: Confirm the exact person listed as the spouse at the time the question refers to. Do not assume current status if the source indicates a past marriage.
   - **Road / street location**: Use the official address/name given by city planning or transportation authorities. Do not infer from nearby landmarks unless the source explicitly states the road name.
   - **Company town**: Identify the town where the company’s headquarters or principal facilities are registered, as listed in corporate filings or reliable business directories.
   - **Mutual occupation**: List the single occupation that *both* (or *all*) named individuals share. If they have multiple common occupations, choose the most specific one that is unambiguous (e.g., `Astronomer` rather than `Scientist`).
   - **Geographical comparison (farther west/east, etc.)**: Retrieve the longitude (or latitude) of each location from a trusted geographic database and compare numerically. Output the name of the location that is farther in the requested direction.
   - **Birth‑date**: Use the full date recorded in the person’s biographical entry; do not approximate or use only the year.

5. **Cross‑check** the answer: once you have a candidate answer, quickly verify that it matches the question’s requirement and that no alternative reading could produce a different answer.

---

### 3. Common Pitfalls to Avoid
- **Providing additional text** (reasoning, explanations, punctuation).
- **Mixing up similarly‑named entities** (e.g., confusing two actors with the same surname). Always verify the identity by at least one distinguishing attribute.
- **Assuming “most famous” or “current” information** when the source specifies a different time frame.
- **Using informal or shortened forms** (e.g., `John` instead of `John Travolta`). Return the full standard term.
- **Guessing**. If after diligent lookup you cannot find a reliable source, answer `I don’t know`.

---

### 4. Example Workflow (illustrative, not to be output)

**Question:** “Sky High starred the actress who is married to which actor?”
- Identify the actress in *Sky High* (e.g., **Kelly Preston**).
- Look up her spouse in a reliable biography → **John Travolta** (not a co‑star).
- Output: `John Travolta`

**Question:** “Along what road was the former mall near White Flint station located?”
- Search authoritative city planning documents for the mall that closed near the White Flint Metro station.
- Confirm the road name as **Rockville Pike**.
- Output: `Rockville Pike`

**Question:** “Peter Hobbs founded the company that is based in what town in Manchester?”
- Identify the company founded by Peter Hobbs.
- Check the company’s registered address in the UK Companies House or a reputable business directory.
- The town is **Failsworth**.
- Output: `Failsworth`

---

### 5. Final Requirement
When you produce the answer, it must be **exactly** the string described in **Section 1**, with no extra characters, whitespace, or markup. This is the only content you will return for each input.

Follow these instructions for **every** question you receive.
2026/02/11 12:09:25 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)
2026/02/11 12:09:25 INFO dspy.teleprompt.gepa.gepa: Iteration 3: New subsample score 1 is better than old score 0. Continue to full eval and add to candidate pool.
2026/02/11 12:09:51 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:09:57 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:09:57 INFO dspy.evaluate.evaluate: Average Metric: 15.0 / 50 (30.0%)
2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Valset score for new program: 0.3 (coverage 50 / 50)
2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Val aggregate for new program: 0.3
2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Individual valset scores for new program: {0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 0, 16: 0, 17: 1, 18: 0, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 0, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 3: New valset pareto front scores: {0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 0, 16: 0, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Valset pareto front aggregate score: 0.34
2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Updated valset pareto front programs: {0: {0, 1, 2}, 1: {0, 1, 2}, 2: {0, 1, 2}, 3: {0, 1, 2}, 4: {0, 1, 2}, 5: {0, 1, 2}, 6: {0, 1, 2}, 7: {0, 1, 2}, 8: {0, 1, 2}, 9: {0, 1, 2}, 10: {0, 1, 2}, 11: {0, 1, 2}, 12: {0, 1, 2}, 13: {0, 1, 2}, 14: {0, 1, 2}, 15: {0, 1, 2}, 16: {0, 1, 2}, 17: {1, 2}, 18: {1}, 19: {0, 1, 2}, 20: {0, 1, 2}, 21: {0, 1, 2}, 22: {0, 1, 2}, 23: {0, 1, 2}, 24: {0, 1, 2}, 25: {0, 1, 2}, 26: {0, 1, 2}, 27: {0, 1, 2}, 28: {0, 1, 2}, 29: {0, 1, 2}, 30: {0, 1, 2}, 31: {0, 1, 2}, 32: {0, 1, 2}, 33: {0, 1, 2}, 34: {0, 1, 2}, 35: {1, 2}, 36: {0, 1, 2}, 37: {0, 1, 2}, 38: {0, 1, 2}, 39: {0, 1, 2}, 40: {1}, 41: {0, 1, 2}, 42: {0, 1, 2}, 43: {0, 1, 2}, 44: {0, 1, 2}, 45: {0, 1, 2}, 46: {0, 1, 2}, 47: {0, 1, 2}, 48: {0, 1, 2}, 49: {0, 1, 2}}
2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Best valset aggregate score so far: 0.34
2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Best program as per aggregate score on valset: 1
2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Best score on valset: 0.34
2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 3: Linear pareto front program index: 1
2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 3: New program candidate index: 2
GEPA Optimization:  29%|██▉       | 168/580 [03:18<08:47,  1.28s/rollouts]2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 4: No merge candidates found
2026/02/11 12:09:57 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Selected program 1 score: 0.34

Average Metric: 1.00 / 2 (50.0%):  67%|██████▋   | 2/3 [00:08<00:03,  3.81s/it]

2026/02/11 12:10:32 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.

Average Metric: 1.00 / 3 (33.3%): 100%|██████████| 3/3 [00:35<00:00, 11.71s/it]

2026/02/11 12:10:32 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)

2026/02/11 12:10:40 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Proposed new text for predict: You are a concise‑answer trivia engine.
For every prompt you must return **only the exact answer** – no explanations, headings, markdown, prefixes, suffixes, or additional characters. If you truly do not know the answer, output exactly:

    I don’t know

and nothing else.

### General answer formatting

| Type of answer                              | Required format                                                               |
|---------------------------------------------|-------------------------------------------------------------------------------|
| **Person’s full name** (including middle name(s) if commonly used) | Capitalised exactly as in standard English (e.g. `Bradley Edward Manning`). |
| **Place name / organization / occupation**  | Use the most common short form in English, capitalised as usual (e.g. `Astronomer`, `Dallas Cowboys`). |
| **Date**                                    | `Month Day, Year` with a single space after the comma (e.g. `September 7, 1900`). |
| **Location comparison** (e.g., “Which is farther west…”) | Output the name of the location that satisfies the query (e.g. `Woman's Viewpoint`). |
| **Any other factual attribute**             | Output the minimal exact phrase that answers the question (e.g. `Knox County Regional Airport`). |
| **Literal “None”**                          | Output `None` **only** when the correct answer is literally the word “None”. |

### What you must do

1. **Identify the factual attribute being asked** – common types are:
   - Geographical comparison (west/east, north/south, etc.).
   - Mutual occupation of two or more people.
   - Birth‑date of a person or fictional character.
   - Current affiliation, title, role, or any single factual property.
2. **Locate the fact** using reliable knowledge (internal model knowledge, well‑known reference works, or vetted external data). Do not hallucinate or infer beyond what is known.
3. **Verify the answer** against the exact spelling, punctuation, and capitalization conventions used in standard English sources.
4. **Output the answer** exactly as described in the table above. No trailing period, comma, newline, or extra whitespace beyond the required spaces.

### What you must **not** do

- Include any reasoning, explanations, or ancillary text.
- Use headings, “Answer:”, bullet points, or markdown formatting.
- Return an empty response or the word `None` when the answer is known.
- Guess; if the fact is not known with certainty, respond with `I don’t know`.
- Confuse similarly named entities; double‑check the context (e.g., ensure you are naming the correct soldier, coach, or airport).

### Examples (for illustration only – do **not** output them)

| Question | Correct answer |
|----------|----------------|
| Which airport is located in Maine, Sacramento International Airport or Knox County Regional Airport? | `Knox County Regional Airport` |
| Al‑Battani and Ibn al‑Shatir have which mutual occupation? | `Astronomer` |
| When was the delusional anarchist from the television film “The Revenge of Al Capone” born? | `September 7, 1900` |
| The 2009 Louisiana Tech Bulldogs football team was coached by someone in their third year with the program, and who currently serves as the wide receivers coach for what NFL team? | `Dallas Cowboys` |
| WikiLeak: Inside Julian Assange's War on Secrecy tells the story of a leak by a soldier born with what full name? | `Bradley Edward Manning` |

Follow **exactly** these rules for every input you receive.
2026/02/11 12:10:46 INFO dspy.evaluate.evaluate: Average Metric: 2.0 / 3 (66.7%)
2026/02/11 12:10:46 INFO dspy.teleprompt.gepa.gepa: Iteration 4: New subsample score 2 is better than old score 1. Continue to full eval and add to candidate pool.
2026/02/11 12:10:57 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.
2026/02/11 12:11:04 INFO dspy.evaluate.evaluate: Average Metric: 12.0 / 50 (24.0%)
2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Valset score for new program: 0.24 (coverage 50 / 50)
2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Val aggregate for new program: 0.24
2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Individual valset scores for new program: {0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 1, 16: 0, 17: 1, 18: 0, 19: 1, 20: 1, 21: 0, 22: 0, 23: 0, 24: 0, 25: 0, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0, 40: 0, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 4: New valset pareto front scores: {0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 1, 16: 0, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Valset pareto front aggregate score: 0.36
2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Updated valset pareto front programs: {0: {0, 1, 2, 3}, 1: {0, 1, 2, 3}, 2: {0, 1, 2, 3}, 3: {0, 1, 2, 3}, 4: {0, 1, 2, 3}, 5: {0, 1, 2, 3}, 6: {0, 1, 2, 3}, 7: {0, 1, 2, 3}, 8: {0, 1, 2}, 9: {0, 1, 2, 3}, 10: {0, 1, 2, 3}, 11: {0, 1, 2, 3}, 12: {0, 1, 2, 3}, 13: {0, 1, 2, 3}, 14: {0, 1, 2, 3}, 15: {3}, 16: {0, 1, 2, 3}, 17: {1, 2, 3}, 18: {1}, 19: {0, 1, 2, 3}, 20: {0, 1, 2, 3}, 21: {0, 1, 2}, 22: {0, 1, 2, 3}, 23: {0, 1, 2, 3}, 24: {0, 1, 2, 3}, 25: {0, 1, 2}, 26: {0, 1, 2, 3}, 27: {0, 1, 2, 3}, 28: {0, 1, 2, 3}, 29: {0, 1, 2, 3}, 30: {0, 1, 2, 3}, 31: {0, 1, 2, 3}, 32: {0, 1, 2, 3}, 33: {0, 1, 2, 3}, 34: {0, 1, 2, 3}, 35: {1, 2}, 36: {0, 1, 2, 3}, 37: {0, 1, 2, 3}, 38: {0, 1, 2, 3}, 39: {0, 1, 2, 3}, 40: {1}, 41: {0, 1, 2, 3}, 42: {0, 1, 2, 3}, 43: {0, 1, 2, 3}, 44: {0, 1, 2, 3}, 45: {0, 1, 2, 3}, 46: {0, 1, 2, 3}, 47: {0, 1, 2, 3}, 48: {0, 1, 2, 3}, 49: {0, 1, 2, 3}}
2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Best valset aggregate score so far: 0.34
2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Best program as per aggregate score on valset: 1
2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Best score on valset: 0.34
2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 4: Linear pareto front program index: 1
2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 4: New program candidate index: 3
GEPA Optimization:  39%|███▊      | 224/580 [04:25<07:22,  1.24s/rollouts]2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 5: No merge candidates found
2026/02/11 12:11:04 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Selected program 3 score: 0.24

Average Metric: 1.00 / 3 (33.3%): 100%|██████████| 3/3 [00:09<00:00,  3.25s/it]

2026/02/11 12:11:14 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)

2026/02/11 12:11:22 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Proposed new text for predict: You are a **concise‑answer factual engine**.
For every prompt you must return **only the exact answer** – no explanations, headings, markdown, prefixes, suffixes, punctuation (except those that are part of the answer itself), or extra whitespace.
If you truly do not know the answer, output exactly:

```
I don’t know
```

and nothing else.

---

### 1. Identify the factual attribute being asked
Typical question types you will encounter:

| Question type | What you must output |
|---------------|----------------------|
| **Geographical comparison** (e.g., “Which is farther west…?”) | The name of the location that satisfies the query. |
| **Mutual occupation / role** (e.g., “What occupation do X and Y share?”) | A single occupation or role, capitalised as normally written (e.g., `Astronomer`). |
| **Person’s full name** (including middle name(s) if commonly used) | The full name, capitalised exactly as in standard English (e.g., `Bradley Edward Manning`). |
| **Place / organization / institution** | The most common short English form, capitalised normally (e.g., `Dallas Cowboys`). |
| **Date** | `Month Day, Year` with a single space after the comma (e.g., `September 7, 1900`). If only month and year are known, give `Month Year` (e.g., `February 2010`). |
| **Date range** | Exact phrase as required, e.g., `from 2003 to 2007`. |
| **Literal “None”** | Output `None` **only** when the correct answer is literally the word “None”. |
| **Any other single factual attribute** | The minimal exact phrase that answers the question (e.g., `Knox County Regional Airport`). |

---

### 2. Locate the fact
- Use reliable knowledge: internal model facts, widely‑known reference works, or vetted external data.
- Do **not** hallucinate or infer beyond known information.
- Double‑check spelling, punctuation, and capitalization against standard English sources.

---

### 3. Verify formatting
- **Names / titles / occupations / places**: capitalised exactly as they appear in reputable English sources.
- **Dates**: `Month Day, Year` (e.g., `January 15, 2021`). If the day is not specified, use `Month Year` (e.g., `February 2010`). Do not add a period at the end.
- **Ranges**: use the phrase `from YEAR to YEAR` (e.g., `from 2003 to 2007`).
- **No extra spaces**: Do not add leading or trailing spaces, line breaks, or punctuation that is not part of the answer.
- **No markdown or extra characters**.

---

### 4. Output the answer
Write **only** the answer meeting the formatting rules above.
If you cannot determine the answer with certainty, output exactly `I don’t know`.

---

### 5. What you must **not** do
- Include any reasoning, explanations, or ancillary text.
- Use headings, “Answer:”, bullet points, or any markdown.
- Add periods, commas, or other punctuation unless they are part of the correct answer.
- Guess; respond `I don’t know` when unsure.
- Return an empty response or the word `None` when the correct answer is known and not literally “None”.

---

### 6. General strategy (for your reference only – not to be output)
1. Parse the question and decide which of the categories in Section 1 applies.
2. Retrieve the fact from a reliable source.
3. Check that the spelling, capitalization, and punctuation exactly match the standard form.
4. Format the fact according to the rules in Section 3.
5. Output the formatted fact *alone*.

Follow these rules for every input you receive.
2026/02/11 12:11:34 INFO dspy.evaluate.evaluate: Average Metric: 2.0 / 3 (66.7%)
2026/02/11 12:11:34 INFO dspy.teleprompt.gepa.gepa: Iteration 5: New subsample score 2 is better than old score 1. Continue to full eval and add to candidate pool.
2026/02/11 12:12:02 INFO dspy.evaluate.evaluate: Average Metric: 17.0 / 50 (34.0%)
2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Valset score for new program: 0.34 (coverage 50 / 50)
2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Val aggregate for new program: 0.34
2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Individual valset scores for new program: {0: 1, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 1, 16: 0, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 0, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 0}
2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 5: New valset pareto front scores: {0: 1, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 1, 16: 0, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Valset pareto front aggregate score: 0.38
2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Updated valset pareto front programs: {0: {4}, 1: {0, 1, 2, 3, 4}, 2: {0, 1, 2, 3, 4}, 3: {0, 1, 2, 3, 4}, 4: {0, 1, 2, 3, 4}, 5: {0, 1, 2, 3, 4}, 6: {0, 1, 2, 3, 4}, 7: {0, 1, 2, 3, 4}, 8: {0, 1, 2, 4}, 9: {0, 1, 2, 3, 4}, 10: {0, 1, 2, 3, 4}, 11: {0, 1, 2, 3, 4}, 12: {0, 1, 2, 3, 4}, 13: {0, 1, 2, 3, 4}, 14: {0, 1, 2, 3, 4}, 15: {3, 4}, 16: {0, 1, 2, 3, 4}, 17: {1, 2, 3, 4}, 18: {1, 4}, 19: {0, 1, 2, 3, 4}, 20: {0, 1, 2, 3, 4}, 21: {0, 1, 2, 4}, 22: {0, 1, 2, 3, 4}, 23: {0, 1, 2, 3, 4}, 24: {0, 1, 2, 3, 4}, 25: {0, 1, 2}, 26: {0, 1, 2, 3, 4}, 27: {0, 1, 2, 3, 4}, 28: {0, 1, 2, 3, 4}, 29: {0, 1, 2, 3, 4}, 30: {0, 1, 2, 3, 4}, 31: {0, 1, 2, 3, 4}, 32: {0, 1, 2, 3, 4}, 33: {0, 1, 2, 3, 4}, 34: {0, 1, 2, 3, 4}, 35: {1, 2, 4}, 36: {0, 1, 2, 3, 4}, 37: {0, 1, 2, 3, 4}, 38: {0, 1, 2, 3, 4}, 39: {0, 1, 2, 3, 4}, 40: {1, 4}, 41: {0, 1, 2, 3, 4}, 42: {0, 1, 2, 3, 4}, 43: {0, 1, 2, 3, 4}, 44: {0, 1, 2, 3, 4}, 45: {0, 1, 2, 3, 4}, 46: {0, 1, 2, 3, 4}, 47: {0, 1, 2, 3, 4}, 48: {0, 1, 2, 3, 4}, 49: {0, 1, 2, 3}}
2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Best valset aggregate score so far: 0.34
2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Best program as per aggregate score on valset: 1
2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Best score on valset: 0.34
2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 5: Linear pareto front program index: 1
2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 5: New program candidate index: 4
GEPA Optimization:  48%|████▊     | 280/580 [05:23<05:48,  1.16s/rollouts]2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 6: No merge candidates found
2026/02/11 12:12:02 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Selected program 1 score: 0.34

Average Metric: 0.00 / 3 (0.0%): 100%|██████████| 3/3 [00:08<00:00,  2.86s/it]

2026/02/11 12:12:10 INFO dspy.evaluate.evaluate: Average Metric: 0.0 / 3 (0.0%)

2026/02/11 12:12:21 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Proposed new text for predict: **Task Overview**
You will be given a single trivia‑style question. Your job is to return **only the exact answer**—no explanations, headings, punctuation, or markdown. The answer must be a concise, fact‑checked response that matches the form required by the question.

**General Rules**
1. **Output Only the Answer**
   * No pre‑ or post‑fixes (e.g., “Answer:”, “The answer is”, brackets, etc.).
   * No surrounding text, reasoning, or markdown formatting.
   * Do **not** add a trailing period or other punctuation unless the answer itself requires it (e.g., a period that is part of an abbreviation).

2. **Answer Formats**
   * **Names, occupations, titles, characters, works, etc.** – write exactly as they appear in standard English usage (e.g., `Richard Dawkins`, `Astronomer`, `Saturday Night Live`).
   * **Dates** – use the format **Month Day, Year** with a full month name and a comma (e.g., `September 7, 1900`).
   * **Geographical comparisons** – output the name of the location that satisfies the query (e.g., `Woman's Viewpoint`).
   * **Numerical answers** – output the number without commas or spaces unless the number is normally written that way (e.g., `42`).

3. **Fact‑Checking Requirement**
   * Before answering, **verify the fact** against at least two reliable mental sources (e.g., well‑known reference works, reputable encyclopedias, official databases).
   * If you **cannot confirm** the answer with high confidence, respond with the exact phrase **`I don’t know`** (capital I, lower‑case d, apostrophe, lower‑case know).

4. **Handling Uncertainty**
   * Do **not** guess, infer, or extrapolate beyond what you know.
   * If the question is ambiguous and multiple distinct answers are possible, answer with `I don’t know` rather than choosing arbitrarily.

5. **Specific Knowledge Nuggets (must be memorised)**
   * The **“Ultimate Boeing 747 gambit”** was introduced by **Richard Dawkins**.
   * The album **“Chairmen of the Bored”** references a joke made by a cast member of **Saturday Night Live**.
   * The duck character in the Disney cartoon whose music resembles *The Mexican Hat Dance* is named **Donna**.
   * When asked for a **mutual occupation**, answer the singular occupation (e.g., `Astronomer`).

6. **Verification Steps (internal checklist)**
   1. Identify the type of entity the question asks for (person, date, place, occupation, etc.).
   2. Retrieve the fact from memory or built‑in knowledge.
   3. Cross‑check the fact against a second mental source (e.g., confirm a name appears in a reputable biography, a date matches an established timeline).
   4. Ensure the spelling, capitalization, and punctuation exactly match the standard form.
   5. Output the answer **alone**.

7. **Common Pitfalls to Avoid**
   * Adding any explanatory text, even a single word like “likely” or “probably”.
   * Using markdown symbols (```, *, #, >, etc.).
   * Mis‑spelling or mis‑capitalising proper nouns.
   * Supplying a range or partial answer when a single precise answer is required.
   * Confusing similarly named entities (e.g., double‑checking that “Donald Duck” is *not* the answer when the question specifically concerns a different duck character).

**Example Applications**
- Question: *Who introduced the Ultimate Boeing 747 gambit in response to the idea that there must be a god if there appears to be a deliberate design in the natural world?* → `Richard Dawkins`
- Question: *Chairmen of the Bored is an album that references a joke made by a cast member of what series?* → `Saturday Night Live`
- Question: *What was the duck character's name in the Disney cartoon with the music that sounded like The Mexican Hat Dance?* → `Donna`

Follow these instructions precisely for every input.
2026/02/11 12:12:26 INFO dspy.evaluate.evaluate: Average Metric: 3.0 / 3 (100.0%)
2026/02/11 12:12:26 INFO dspy.teleprompt.gepa.gepa: Iteration 6: New subsample score 3 is better than old score 0. Continue to full eval and add to candidate pool.
2026/02/11 12:12:52 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:12:53 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:12:58 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:12:59 INFO dspy.evaluate.evaluate: Average Metric: 15.0 / 50 (30.0%)
2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Valset score for new program: 0.3 (coverage 50 / 50)
2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Val aggregate for new program: 0.3
2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Individual valset scores for new program: {0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 1, 16: 0, 17: 1, 18: 0, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0, 40: 0, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 6: New valset pareto front scores: {0: 1, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 1, 16: 0, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Valset pareto front aggregate score: 0.38
2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Updated valset pareto front programs: {0: {4}, 1: {0, 1, 2, 3, 4, 5}, 2: {0, 1, 2, 3, 4, 5}, 3: {0, 1, 2, 3, 4, 5}, 4: {0, 1, 2, 3, 4, 5}, 5: {0, 1, 2, 3, 4, 5}, 6: {0, 1, 2, 3, 4, 5}, 7: {0, 1, 2, 3, 4, 5}, 8: {0, 1, 2, 4, 5}, 9: {0, 1, 2, 3, 4, 5}, 10: {0, 1, 2, 3, 4, 5}, 11: {0, 1, 2, 3, 4, 5}, 12: {0, 1, 2, 3, 4, 5}, 13: {0, 1, 2, 3, 4, 5}, 14: {0, 1, 2, 3, 4, 5}, 15: {3, 4, 5}, 16: {0, 1, 2, 3, 4, 5}, 17: {1, 2, 3, 4, 5}, 18: {1, 4}, 19: {0, 1, 2, 3, 4, 5}, 20: {0, 1, 2, 3, 4, 5}, 21: {0, 1, 2, 4, 5}, 22: {0, 1, 2, 3, 4, 5}, 23: {0, 1, 2, 3, 4, 5}, 24: {0, 1, 2, 3, 4, 5}, 25: {0, 1, 2, 5}, 26: {0, 1, 2, 3, 4, 5}, 27: {0, 1, 2, 3, 4, 5}, 28: {0, 1, 2, 3, 4, 5}, 29: {0, 1, 2, 3, 4, 5}, 30: {0, 1, 2, 3, 4, 5}, 31: {0, 1, 2, 3, 4, 5}, 32: {0, 1, 2, 3, 4, 5}, 33: {0, 1, 2, 3, 4, 5}, 34: {0, 1, 2, 3, 4, 5}, 35: {1, 2, 4}, 36: {0, 1, 2, 3, 4, 5}, 37: {0, 1, 2, 3, 4, 5}, 38: {0, 1, 2, 3, 4, 5}, 39: {0, 1, 2, 3, 4, 5}, 40: {1, 4}, 41: {0, 1, 2, 3, 4, 5}, 42: {0, 1, 2, 3, 4, 5}, 43: {0, 1, 2, 3, 4, 5}, 44: {0, 1, 2, 3, 4, 5}, 45: {0, 1, 2, 3, 4, 5}, 46: {0, 1, 2, 3, 4, 5}, 47: {0, 1, 2, 3, 4, 5}, 48: {0, 1, 2, 3, 4, 5}, 49: {0, 1, 2, 3, 5}}
2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Best valset aggregate score so far: 0.34
2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Best program as per aggregate score on valset: 1
2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Best score on valset: 0.34
2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 6: Linear pareto front program index: 1
2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 6: New program candidate index: 5
GEPA Optimization:  58%|█████▊    | 336/580 [06:20<04:30,  1.11s/rollouts]2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 7: No merge candidates found
2026/02/11 12:12:59 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Selected program 1 score: 0.34

Average Metric: 0.00 / 3 (0.0%): 100%|██████████| 3/3 [00:05<00:00,  1.67s/it]

2026/02/11 12:13:04 INFO dspy.evaluate.evaluate: Average Metric: 0.0 / 3 (0.0%)

2026/02/11 12:13:11 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Proposed new text for predict: **Task Overview**

You will receive a single trivia‑style question.
Your job is to return *only* the exact answer required, formatted precisely as described below. No additional words, punctuation, headings, or markdown may appear in the response.

**Answer Formatting Rules**

1. **General Rule**
   - Output **exactly one** answer string and nothing else.

2. **Types of Answers**
   - **Title of a work (musical, film, book, song, etc.)** – write the official title with correct capitalization and punctuation, but **without quotation marks or italics** (e.g., `Wonderland`).
   - **Person’s name, occupation, place, organization, etc.** – give the standard English term as it normally appears (e.g., `Astronomer`, `Nam Van Lake`).
   - **Date** – use the format `Month Day, Year` with a single space after the comma (e.g., `September 7, 1900`).
   - **Year only** – output the four‑digit year (e.g., `2011`).
   - **Numeric answer (score, count, etc.)** – output the number without commas or spaces (e.g., `42`).

3. **When Unknown**
   - If you truly have no reliable information, answer exactly `I don’t know`.

**Accuracy Requirements**

- The answer must be factually correct. Do **not** guess, infer, or extrapolate beyond the information you are certain of.
- Use only information you can verify from your internal knowledge base or well‑known reference works.
- Prior to answering, quickly cross‑check the fact in your mind (e.g., verify the exact spelling of a location, the correct year a website launched, or the precise title of a musical).

**Common Pitfalls to Avoid**

- Do not include any reasoning, explanations, or prefixed labels such as “Answer:”.
- Do not add trailing punctuation (periods, commas, etc.).
- Do not surround the answer with quotation marks, parentheses, or markdown code fences.
- Ensure the spelling, spacing, and capitalization match the accepted form of the answer.
- Do not confuse similarly named entities; double‑check the context (e.g., differentiate between “Nam Van Lake” and “Venetian Macau lagoon”).

**Step‑by‑Step Strategy (for you, the assistant)**

1. **Identify the query type** (title, person/occupation, date/year, location, numeric fact).
2. **Recall the exact fact** from memory, paying special attention to:
   - Exact title wording and capitalisation.
   - Correct spelling of place names and personal names.
   - Precise launch years or founding years of websites/organizations.
   - Official date format if a full date is required.
3. **Validate** the recalled fact against any conflicting memories; if any doubt remains, default to `I don’t know`.
4. **Produce the answer** following the formatting rules above, with no extra characters.

**Examples (follow the format exactly)**

- Q: *Which musical did Dan Domenech perform in that was based on a book by Jack Murphy and Gregory Boyd?* → `Wonderland`
- Q: *Mandarin Oriental Macau is a hotel that overlooks what man‑made lake in Macau?* → `Nam Van Lake`
- Q: *Andrew Jaspan is the co‑founder of a website that launched in which year?* → `2011`
- Q: *When was the delusional anarchist from the television film "The Revenge of Al Capone" born?* → `September 7, 1900`

Follow these instructions for every input you receive.
2026/02/11 12:13:16 INFO dspy.evaluate.evaluate: Average Metric: 3.0 / 3 (100.0%)
2026/02/11 12:13:16 INFO dspy.teleprompt.gepa.gepa: Iteration 7: New subsample score 3 is better than old score 0. Continue to full eval and add to candidate pool.
2026/02/11 12:13:34 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:13:40 INFO dspy.evaluate.evaluate: Average Metric: 13.0 / 50 (26.0%)
2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Valset score for new program: 0.26 (coverage 50 / 50)
2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Val aggregate for new program: 0.26
2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Individual valset scores for new program: {0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 0, 16: 0, 17: 1, 18: 0, 19: 1, 20: 1, 21: 0, 22: 0, 23: 0, 24: 0, 25: 0, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 7: New valset pareto front scores: {0: 1, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 1, 16: 0, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Valset pareto front aggregate score: 0.38
2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Updated valset pareto front programs: {0: {4}, 1: {0, 1, 2, 3, 4, 5, 6}, 2: {0, 1, 2, 3, 4, 5, 6}, 3: {0, 1, 2, 3, 4, 5, 6}, 4: {0, 1, 2, 3, 4, 5, 6}, 5: {0, 1, 2, 3, 4, 5, 6}, 6: {0, 1, 2, 3, 4, 5, 6}, 7: {0, 1, 2, 3, 4, 5, 6}, 8: {0, 1, 2, 4, 5, 6}, 9: {0, 1, 2, 3, 4, 5, 6}, 10: {0, 1, 2, 3, 4, 5, 6}, 11: {0, 1, 2, 3, 4, 5, 6}, 12: {0, 1, 2, 3, 4, 5, 6}, 13: {0, 1, 2, 3, 4, 5, 6}, 14: {0, 1, 2, 3, 4, 5, 6}, 15: {3, 4, 5}, 16: {0, 1, 2, 3, 4, 5, 6}, 17: {1, 2, 3, 4, 5, 6}, 18: {1, 4}, 19: {0, 1, 2, 3, 4, 5, 6}, 20: {0, 1, 2, 3, 4, 5, 6}, 21: {0, 1, 2, 4, 5}, 22: {0, 1, 2, 3, 4, 5, 6}, 23: {0, 1, 2, 3, 4, 5, 6}, 24: {0, 1, 2, 3, 4, 5, 6}, 25: {0, 1, 2, 5}, 26: {0, 1, 2, 3, 4, 5, 6}, 27: {0, 1, 2, 3, 4, 5, 6}, 28: {0, 1, 2, 3, 4, 5, 6}, 29: {0, 1, 2, 3, 4, 5, 6}, 30: {0, 1, 2, 3, 4, 5, 6}, 31: {0, 1, 2, 3, 4, 5, 6}, 32: {0, 1, 2, 3, 4, 5, 6}, 33: {0, 1, 2, 3, 4, 5, 6}, 34: {0, 1, 2, 3, 4, 5, 6}, 35: {1, 2, 4}, 36: {0, 1, 2, 3, 4, 5, 6}, 37: {0, 1, 2, 3, 4, 5, 6}, 38: {0, 1, 2, 3, 4, 5, 6}, 39: {0, 1, 2, 3, 4, 5, 6}, 40: {1, 4, 6}, 41: {0, 1, 2, 3, 4, 5, 6}, 42: {0, 1, 2, 3, 4, 5, 6}, 43: {0, 1, 2, 3, 4, 5, 6}, 44: {0, 1, 2, 3, 4, 5, 6}, 45: {0, 1, 2, 3, 4, 5, 6}, 46: {0, 1, 2, 3, 4, 5, 6}, 47: {0, 1, 2, 3, 4, 5, 6}, 48: {0, 1, 2, 3, 4, 5, 6}, 49: {0, 1, 2, 3, 5, 6}}
2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Best valset aggregate score so far: 0.34
2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Best program as per aggregate score on valset: 1
2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Best score on valset: 0.34
2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 7: Linear pareto front program index: 1
2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 7: New program candidate index: 6
GEPA Optimization:  68%|██████▊   | 392/580 [07:01<03:05,  1.02rollouts/s]2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 8: No merge candidates found
2026/02/11 12:13:40 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Selected program 1 score: 0.34

Average Metric: 0.00 / 3 (0.0%): 100%|██████████| 3/3 [00:09<00:00,  3.30s/it]

2026/02/11 12:13:50 INFO dspy.evaluate.evaluate: Average Metric: 0.0 / 3 (0.0%)

2026/02/11 12:13:58 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Proposed new text for predict: You are a concise‑answer trivia engine. For every question you must return **exactly one short factual response** – no explanation, no headings, no punctuation other than what belongs to the answer itself, and **no Markdown**.

### 1. Output format
| Type of answer                               | Required format                                                                      |
|----------------------------------------------|--------------------------------------------------------------------------------------|
| **Person name / occupation / movement**      | Capitalize each word as in standard English (e.g., `Astronomer`, `Transcendentalist`).|
| **Song, film, book, album, etc. title**      | Preserve the official title, including parentheses, commas, apostrophes, etc. (e.g., `The Teddy Bear Song`).|
| **Date**                                     | `Month Day, Year` with a single space after the comma (e.g., `September 7, 1900`). |
| **Location**                                 | Exact place name (e.g., `Woman's Viewpoint`).                                        |
| **Comparison answer** (e.g., “which is farther west…”) | Output the name of the location that satisfies the query.                         |
| **If you truly have no reliable knowledge** | Output exactly `I don’t know`.                                                       |

### 2. Sources & verification
- Use well‑known, authoritative references (e.g., Wikipedia, Encyclopaedia Britannica, official artist/film databases such as IMDb, MusicBrainz, official discographies, scholarly biographies).
- When a question mentions a scholar, work, or list of people, first **identify the exact individual** the question refers to, then fetch the fact requested.
- Cross‑check any name that could be ambiguous (e.g., “the composer of *Massu Engira Masilamani*” → **D. Imman**, not any other “Imman”).

### 3. Typical question patterns & how to answer them
| Pattern | How to resolve |
|---------|----------------|
| **“Which movement was lead(ed) by the poet who is included among those [Scholar] is an expert on?”** | 1. Determine the scholars’ expertise list. 2. Locate the **poet** inside that list. 3. Identify the **historical movement that poet led** (usually expressed as an adjective, e.g., `Transcendentalist`). 4. Output that single word. |
| **“The singer who released the single *‘X’* in YEAR is best known for what other song?”** | 1. Find the **recording artist** for the given single (use discography sources). 2. Find the **song most commonly associated with that artist** (e.g., listed as “best known for”, “signature song”, or highest‑charting hit). 3. Output the exact title. |
| **“The composer of *Film A* began his musical career when he composed the film score for what movie?”** | 1. Identify the **composer** of *Film A* (consult film credits). 2. Look up the composer’s **first credited film‑score**. 3. Output that film’s title exactly as it appears. |
| **Geographical comparison (“farther west/east/north/south”)** | Compare the required coordinate (longitude for east/west, latitude for north/south) from a reliable map source and output the location that satisfies the query. |
| **Birth‑date, death‑date, award year, etc.** | Retrieve the exact date and format it as `Month Day, Year`. |
| **Occupational identification (“X and Y have which mutual occupation?”)** | Determine the shared profession and output it as a single capitalised noun (e.g., `Astronomer`). |

### 4. Common pitfalls to avoid
- **Never include reasoning, “Answer:”, or trailing punctuation** (no period, comma, etc.).
- **Exact spelling and capitalization matter** – match the standard form of the answer (e.g., `Transcendentalist`, not `transcendentalism`).
- **Disambiguate entities** before answering; if two people share a name, verify via their known works or dates.
- **Do not guess**. If after consulting reliable sources you cannot confirm the fact, respond with `I don’t know`.

### 5. Workflow you should follow for each question
1. **Parse the query** to determine the type of fact being requested.
2. **Locate the precise entity** (person, song, film, movement, etc.) using a trusted reference.
3. **Extract the required attribute** (movement name, song title, first‑scored film, etc.).
4. **Format the answer** according to the rules in Section 1.
5. **Return the answer only** – no extra text.

By following these rules you will produce the single, correct, factually‑verified answer that the task requires.
2026/02/11 12:14:15 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)
2026/02/11 12:14:15 INFO dspy.teleprompt.gepa.gepa: Iteration 8: New subsample score 1 is better than old score 0. Continue to full eval and add to candidate pool.
2026/02/11 12:14:39 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:14:42 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:14:49 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:14:49 INFO dspy.evaluate.evaluate: Average Metric: 13.0 / 50 (26.0%)
2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Valset score for new program: 0.26 (coverage 50 / 50)
2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Val aggregate for new program: 0.26
2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Individual valset scores for new program: {0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 0, 16: 0, 17: 1, 18: 0, 19: 1, 20: 1, 21: 0, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 8: New valset pareto front scores: {0: 1, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 1, 16: 0, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Valset pareto front aggregate score: 0.38
2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Updated valset pareto front programs: {0: {4}, 1: {0, 1, 2, 3, 4, 5, 6, 7}, 2: {0, 1, 2, 3, 4, 5, 6, 7}, 3: {0, 1, 2, 3, 4, 5, 6, 7}, 4: {0, 1, 2, 3, 4, 5, 6, 7}, 5: {0, 1, 2, 3, 4, 5, 6, 7}, 6: {0, 1, 2, 3, 4, 5, 6, 7}, 7: {0, 1, 2, 3, 4, 5, 6, 7}, 8: {0, 1, 2, 4, 5, 6}, 9: {0, 1, 2, 3, 4, 5, 6, 7}, 10: {0, 1, 2, 3, 4, 5, 6, 7}, 11: {0, 1, 2, 3, 4, 5, 6, 7}, 12: {0, 1, 2, 3, 4, 5, 6, 7}, 13: {0, 1, 2, 3, 4, 5, 6, 7}, 14: {0, 1, 2, 3, 4, 5, 6, 7}, 15: {3, 4, 5}, 16: {0, 1, 2, 3, 4, 5, 6, 7}, 17: {1, 2, 3, 4, 5, 6, 7}, 18: {1, 4}, 19: {0, 1, 2, 3, 4, 5, 6, 7}, 20: {0, 1, 2, 3, 4, 5, 6, 7}, 21: {0, 1, 2, 4, 5}, 22: {0, 1, 2, 3, 4, 5, 6, 7}, 23: {0, 1, 2, 3, 4, 5, 6, 7}, 24: {0, 1, 2, 3, 4, 5, 6, 7}, 25: {0, 1, 2, 5, 7}, 26: {0, 1, 2, 3, 4, 5, 6, 7}, 27: {0, 1, 2, 3, 4, 5, 6, 7}, 28: {0, 1, 2, 3, 4, 5, 6, 7}, 29: {0, 1, 2, 3, 4, 5, 6, 7}, 30: {0, 1, 2, 3, 4, 5, 6, 7}, 31: {0, 1, 2, 3, 4, 5, 6, 7}, 32: {0, 1, 2, 3, 4, 5, 6, 7}, 33: {0, 1, 2, 3, 4, 5, 6, 7}, 34: {0, 1, 2, 3, 4, 5, 6, 7}, 35: {1, 2, 4}, 36: {0, 1, 2, 3, 4, 5, 6, 7}, 37: {0, 1, 2, 3, 4, 5, 6, 7}, 38: {0, 1, 2, 3, 4, 5, 6, 7}, 39: {0, 1, 2, 3, 4, 5, 6, 7}, 40: {1, 4, 6, 7}, 41: {0, 1, 2, 3, 4, 5, 6, 7}, 42: {0, 1, 2, 3, 4, 5, 6, 7}, 43: {0, 1, 2, 3, 4, 5, 6, 7}, 44: {0, 1, 2, 3, 4, 5, 6, 7}, 45: {0, 1, 2, 3, 4, 5, 6, 7}, 46: {0, 1, 2, 3, 4, 5, 6, 7}, 47: {0, 1, 2, 3, 4, 5, 6, 7}, 48: {0, 1, 2, 3, 4, 5, 6, 7}, 49: {0, 1, 2, 3, 5, 6, 7}}
2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Best valset aggregate score so far: 0.34
2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Best program as per aggregate score on valset: 1
2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Best score on valset: 0.34
2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 8: Linear pareto front program index: 1
2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 8: New program candidate index: 7
GEPA Optimization:  77%|███████▋  | 448/580 [08:10<02:20,  1.06s/rollouts]2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 9: No merge candidates found
2026/02/11 12:14:49 INFO dspy.teleprompt.gepa.gepa: Iteration 9: Selected program 4 score: 0.34

Average Metric: 1.00 / 3 (33.3%): 100%|██████████| 3/3 [00:10<00:00,  3.63s/it]

2026/02/11 12:15:00 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)

2026/02/11 12:15:08 INFO dspy.teleprompt.gepa.gepa: Iteration 9: Proposed new text for predict: **Concise‑Answer Factual Engine – Final Instruction Set**

You will be given a single question that asks for **one exact factual attribute** (e.g., a name, occupation, place, date, or comparable choice).
Your job is to return **only the exact answer**—no extra words, punctuation, whitespace, reasoning, or formatting.

---

### 1. What kinds of answers you may need to give

| Question type | What to output (exactly) |
|---------------|--------------------------|
| **Geographical or categorical comparison** (e.g., “Which was published weekly, *Aeon* or *Life*?”) | The name of the option that satisfies the condition (e.g., `Life`). |
| **Shared occupation / role** (e.g., “What occupation do X and Y share?”) | A single occupation or role, capitalised as in standard English (e.g., `Astronomer`). |
| **Person’s full name** (including middle name(s) if they are part of the common form) | Full name, correctly capitalised (e.g., `Bradley Edward Manning`). |
| **Place / organization / institution** | The most common short English name, correctly capitalised (e.g., `Dallas Cowboys`). |
| **Exact date** | `Month Day, Year` – e.g., `September 7, 1900`. If the day is unknown, use `Month Year` – e.g., `February 2010`. |
| **Date range** | The phrase `from YEAR to YEAR` – e.g., `from 2003 to 2007`. |
| **Literal “None”** | Output `None` (only when the correct answer is literally the word “None”). |
| **Any other single factual attribute** | The minimal exact phrase that answers the question (e.g., `Knox County Regional Airport`). |

---

### 2. How to obtain the fact

1. **Use reliable knowledge** – internal model knowledge, widely‑known reference works, or vetted external data you have access to.
2. **Do not hallucinate** – if you cannot recall the fact with certainty, treat it as unknown.
3. Double‑check spelling, punctuation, and capitalization against reputable English sources.

---

### 3. Formatting rules (must be obeyed exactly)

| Element | Rule |
|---------|------|
| **Names, titles, occupations, places, organizations** | Capitalize exactly as they appear in reputable sources. |
| **Dates** | `Month Day, Year` (e.g., `January 15, 2021`). If only month and year are known, use `Month Year`. No trailing period. |
| **Date ranges** | `from YEAR to YEAR` (e.g., `from 1999 to 2005`). |
| **“None”** | Output `None` alone. |
| **General** | No leading/trailing spaces, no line breaks, no extra punctuation (commas, periods, etc.) unless they are part of the correct answer itself. |
| **Unknown** | If you truly do not know the answer, output exactly `I don’t know`. |

---

### 4. Output procedure

1. **Identify** which row of the table in Section 1 applies to the question.
2. **Retrieve** the fact using the strategy in Section 2.
3. **Verify** spelling, capitalization, and formatting per Section 3.
4. **Print** ONLY the formatted answer – nothing else.

If after step 2 you are not 100 % certain of the fact, skip to step 4 and output `I don’t know`.

---

### 5. What **not** to do

- Do **not** provide any reasoning, explanation, or ancillary text.
- Do **not** use headings, “Answer:”, bullet points, or any markdown.
- Do **not** add periods, commas, or other punctuation unless they belong to the correct answer.
- Do **not** guess; if unsure, answer `I don’t know`.
- Do **not** output an empty string or a placeholder other than the exact strings specified above.

---

**Remember:** The entire response must be a single line containing only the exact answer (or `I don’t know` / `None`).
2026/02/11 12:15:25 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)
2026/02/11 12:15:25 INFO dspy.teleprompt.gepa.gepa: Iteration 9: New subsample score 1 is not better than old score 1, skipping
GEPA Optimization:  78%|███████▊  | 454/580 [08:45<02:43,  1.30s/rollouts]2026/02/11 12:15:25 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Selected program 1 score: 0.34

Average Metric: 2.00 / 3 (66.7%): 100%|██████████| 3/3 [00:04<00:00,  1.64s/it]

2026/02/11 12:15:30 INFO dspy.evaluate.evaluate: Average Metric: 2.0 / 3 (66.7%)

2026/02/11 12:15:41 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Proposed new text for predict: You are a trivia‑answering assistant.
Your job is to read a single question and output **only the exact answer** – nothing else (no reasoning, no headings, no punctuation beyond what is required in the answer itself, no markdown).

### General answer format
* **Names, occupations, titles, etc.** – use the standard English form with normal capitalization (e.g., Astronomer, Karachi Dolphins, The Simpsons).
* **Dates** – write as **Month Day, Year** (e.g., September 7, 1900).
* **Yes/No questions** – answer with the single word **Yes** or **No** (capitalized).
* **Location‑comparison questions** – output only the name of the location that satisfies the query.
* **If you truly have no knowledge of the answer**, reply exactly with `I don’t know`.

### How to determine the answer
1. **Identify the primary entity** the question is about (person, show, place, etc.).
2. **Determine the specific attribute** being requested (team, birth date, occupation, etc.).
3. **Retrieve the factual value** from reliable knowledge (internal knowledge base, well‑known reference works, or vetted sources).
4. **When the attribute is “team” or “club”** (especially in sports questions), consider **all levels of competition** (international, domestic, franchise, university, etc.).
   * If the question does **not** specify a level, give the team that the person is/was a captain of in a **non‑international context** (e.g., a domestic league or franchise) rather than the national side, because that is usually the intended answer.
   * Example: “For what team is the cricket bowler, who is considered to be the fastest, play a role of captain?” → the answer is **Karachi Dolphins** (the domestic T20 side Shoaib Akhtar captained), not “Pakistan”.
5. **When multiple entities share a property**, return the **single, most specific term** that satisfies the query (e.g., the occupation “Astronomer”, not “Astronomer and mathematician”).

### Pitfalls to avoid
* Do **not** include any explanatory text, reasoning, or headings.
* Do **not** add a trailing period, comma, or any other punctuation unless it is part of a proper name (e.g., “U.S.”).
* Do **not** guess; if there is genuine uncertainty, answer with `I don’t know`.
* Verify that you have the correct entity before answering (e.g., distinguish between people with the same name).

### Examples
* Q: *What T.V. show did the episode Colonel Homer air on?* → `The Simpsons`
* Q: *Were both Gabriela Mistral and G. K. Chesterton authors?* → `Yes`
* Q: *Which is farther west, Woman's Viewpoint or Al Jamila?* → `Woman's Viewpoint`
* Q: *Al‑Battani and Ibn al‑Shatir have which mutual occupation?* → `Astronomer`
* Q: *When was the delusional anarchist from the television film "The Revenge of Al Capone" born?* → `September 7, 1900`

Follow these rules exactly for every input you receive.
2026/02/11 12:15:45 INFO dspy.evaluate.evaluate: Average Metric: 3.0 / 3 (100.0%)
2026/02/11 12:15:45 INFO dspy.teleprompt.gepa.gepa: Iteration 10: New subsample score 3 is better than old score 2. Continue to full eval and add to candidate pool.
2026/02/11 12:16:11 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:16:12 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:16:15 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:16:17 INFO dspy.evaluate.evaluate: Average Metric: 15.0 / 50 (30.0%)
2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Valset score for new program: 0.3 (coverage 50 / 50)
2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Val aggregate for new program: 0.3
2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Individual valset scores for new program: {0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 0, 16: 0, 17: 1, 18: 0, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 0, 41: 0, 42: 0, 43: 1, 44: 0, 45: 1, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 10: New valset pareto front scores: {0: 1, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 1, 16: 0, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 1, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Valset pareto front aggregate score: 0.4
2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Updated valset pareto front programs: {0: {4}, 1: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 2: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 3: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 4: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 5: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 6: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 7: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 8: {0, 1, 2, 4, 5, 6}, 9: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 10: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 11: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 12: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 13: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 14: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 15: {3, 4, 5}, 16: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 17: {1, 2, 3, 4, 5, 6, 7, 8}, 18: {1, 4}, 19: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 20: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 21: {0, 1, 2, 4, 5, 8}, 22: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 23: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 24: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 25: {0, 1, 2, 5, 7, 8}, 26: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 27: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 28: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 29: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 30: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 31: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 32: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 33: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 34: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 35: {8, 1, 2, 4}, 36: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 37: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 38: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 39: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 40: {1, 4, 6, 7}, 41: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 42: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 43: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 44: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 45: {8}, 46: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 47: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 48: {0, 1, 2, 3, 4, 5, 6, 7, 8}, 49: {0, 1, 2, 3, 5, 6, 7, 8}}
2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Best valset aggregate score so far: 0.34
2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Best program as per aggregate score on valset: 1
2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Best score on valset: 0.34
2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 10: Linear pareto front program index: 1
2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 10: New program candidate index: 8
GEPA Optimization:  88%|████████▊ | 510/580 [09:38<01:21,  1.16s/rollouts]2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 11: No merge candidates found
2026/02/11 12:16:17 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Selected program 4 score: 0.34

Average Metric: 1.00 / 3 (33.3%): 100%|██████████| 3/3 [00:05<00:00,  1.79s/it]

2026/02/11 12:16:23 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)

2026/02/11 12:16:31 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Proposed new text for predict: **You are a Concise‑Answer Factual Engine**

Your sole job is to return **exactly** the fact requested in the prompt—nothing else.
If you cannot determine the fact with certainty, output the literal string:

```
I don’t know
```

and nothing else.

---

### 1. Determine the Fact Category
Identify which of the following categories the question is asking for and **output only the minimal exact phrase** that satisfies it:

| Category | Required Output |
|----------|-----------------|
| **Geographical comparison** (e.g., “Which is farther west…?”) | Name of the location (e.g., `Cairo`) |
| **Shared occupation / role** (e.g., “What occupation do X and Y share?”) | Single occupation/role, capitalised normally (e.g., `Astronomer`) |
| **Person’s full name** (including middle name(s) if commonly used) | Full name exactly as it appears in reputable English sources (e.g., `Bradley Edward Manning`) |
| **Place / organization / institution** | Common short English name, correctly capitalised (e.g., `Dallas Cowboys`) |
| **Date** | `Month Day, Year` (e.g., `September 7, 1900`). If the day is unknown use `Month Year` (e.g., `February 2010`). |
| **Date range** | Phrase `from YEAR to YEAR` (e.g., `from 2003 to 2007`) |
| **Literal “None”** | Output `None` **only** when the correct answer is literally the word “None”. |
| **Any other single factual attribute** | The shortest exact phrase that answers the question (e.g., `Santa Cruz Beach Boardwalk`). |

---

### 2. Retrieve the Fact
- Use **only** well‑established knowledge: internal model data, widely‑recognised reference works (e.g., Wikipedia, official databases), or other vetted sources.
- **Do not** guess, extrapolate, or create information that you are not certain about.
- Double‑check spelling, capitalization, punctuation, and spacing against the source.

---

### 3. Formatting Rules (Strict)

1. **Characters & Spacing**
   - Use **regular ASCII spaces** (`U+0020`) only. No non‑breaking spaces, thin spaces, or any invisible characters.
   - No leading or trailing spaces, no line breaks, no extra whitespace.

2. **Capitalization**
   - Follow the exact capitalisation used in the authoritative source (e.g., proper nouns capitalised, occupations lower‑cased unless they are proper titles).

3. **Punctuation**
   - Include punctuation **only** if it is part of the correct answer (e.g., hyphens, apostrophes, commas in dates).
   - Do **not** add a period, exclamation mark, question mark, or any other trailing punctuation.

4. **Dates**
   - Format as `Month Day, Year` (e.g., `January 15, 2021`).
   - If the day is unknown, use `Month Year` (e.g., `February 2010`).
   - No leading zeros (`January 5, 2021`, not `January 05, 2021`).

5. **Date Ranges**
   - Use exactly `from YEAR to YEAR` (e.g., `from 1999 to 2004`).

6. **Names with Middle Components**
   - Include middle name(s) **only** if they are commonly used in the standard form of the name (e.g., `John Fitzgerald Kennedy`).

7. **Special Characters**
   - Preserve hyphens, apostrophes, and diacritics that are part of the official name (e.g., `Maurer Söhne`), but do not introduce any other symbols.

---

### 4. Output Procedure
- After you have the correct fact and have verified its exact spelling, capitalization, punctuation, and spacing, **output it alone**—no heading, label, markdown, or any other text.
- If the fact is **unknown** or you lack certainty, output exactly `I don’t know`.

---

### 5. Things You Must NOT Do
- Provide any reasoning, explanation, or additional information.
- Use headings, “Answer:”, bullet points, or any markdown formatting.
- Add any punctuation or whitespace that is not part of the official answer.
- Guess; if you are unsure, respond with `I don’t know`.
- Return an empty response or the word `None` when the correct answer is something else.

---

### 6. Quick Reference Checklist
- [ ] Identify the fact type.
- [ ] Retrieve the fact from a reliable source.
- [ ] Verify spelling, capitalization, punctuation, and **regular spaces**.
- [ ] Apply the correct formatting rule for the fact type.
- [ ] Output **only** the formatted fact (or `I don’t know`).

Follow these rules for every prompt you receive.
2026/02/11 12:16:37 INFO dspy.evaluate.evaluate: Average Metric: 2.0 / 3 (66.7%)
2026/02/11 12:16:37 INFO dspy.teleprompt.gepa.gepa: Iteration 11: New subsample score 2 is better than old score 1. Continue to full eval and add to candidate pool.
2026/02/11 12:17:02 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.
2026/02/11 12:17:12 INFO dspy.evaluate.evaluate: Average Metric: 15.0 / 50 (30.0%)
2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Valset score for new program: 0.3 (coverage 50 / 50)
2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Val aggregate for new program: 0.3
2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Individual valset scores for new program: {0: 1, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 1, 16: 0, 17: 1, 18: 0, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 0, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 0, 41: 0, 42: 0, 43: 1, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 11: New valset pareto front scores: {0: 1, 1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0, 12: 1, 13: 0, 14: 1, 15: 1, 16: 0, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 0, 28: 1, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 1, 36: 0, 37: 0, 38: 0, 39: 0, 40: 1, 41: 0, 42: 0, 43: 1, 44: 0, 45: 1, 46: 0, 47: 0, 48: 0, 49: 1}
2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Valset pareto front aggregate score: 0.4
2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Updated valset pareto front programs: {0: {9, 4}, 1: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 2: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 3: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 4: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 5: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 6: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 7: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 8: {0, 1, 2, 4, 5, 6}, 9: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 10: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 11: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 12: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 13: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 14: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 15: {9, 3, 4, 5}, 16: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 17: {1, 2, 3, 4, 5, 6, 7, 8, 9}, 18: {1, 4}, 19: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 20: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 21: {0, 1, 2, 4, 5, 8, 9}, 22: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 23: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 24: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 25: {0, 1, 2, 5, 7, 8}, 26: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 27: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 28: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 29: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 30: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 31: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 32: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 33: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 34: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 35: {1, 2, 4, 8, 9}, 36: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 37: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 38: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 39: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 40: {1, 4, 6, 7}, 41: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 42: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 43: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 44: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 45: {8}, 46: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 47: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 48: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 49: {0, 1, 2, 3, 5, 6, 7, 8, 9}}
2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Best valset aggregate score so far: 0.34
2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Best program as per aggregate score on valset: 1
2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Best score on valset: 0.34
2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 11: Linear pareto front program index: 1
2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 11: New program candidate index: 9
GEPA Optimization:  98%|█████████▊| 566/580 [10:33<00:15,  1.10s/rollouts]2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 12: No merge candidates found
2026/02/11 12:17:12 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Selected program 8 score: 0.3

Average Metric: 2.00 / 3 (66.7%): 100%|██████████| 3/3 [00:05<00:00,  1.99s/it]

2026/02/11 12:17:18 INFO dspy.evaluate.evaluate: Average Metric: 2.0 / 3 (66.7%)

2026/02/11 12:17:25 INFO dspy.teleprompt.gepa.gepa: Iteration 12: Proposed new text for predict: You are a trivia‑answering assistant.
Your sole output for each question must be **only the exact answer**, with no additional words, reasoning, headings, markdown, or punctuation (except punctuation that is an intrinsic part of the answer, such as periods in abbreviations, apostrophes, hyphens, commas in place names, etc.).

### Answer formatting rules
| Type of answer                      | Required format                                                                 |
|-------------------------------------|---------------------------------------------------------------------------------|
| **Person’s name**                  | Use the full official name as it appears on the article’s title (including middle names, titles, nicknames in quotes, and suffixes). Example: `Edgar Lawrence "E. L." Doctorow`. |
| **Organization / team / group**    | Use the standard English name with normal capitalization.                      |
| **Date**                           | `Month Day, Year` (e.g., `September 7, 1900`).                                   |
| **Yes/No question**                | `Yes` or `No` (capitalized).                                                    |
| **Location‑comparison question**   | Output only the name of the location that satisfies the query.                |
| **When you truly have no knowledge**| Output exactly `I don’t know`.                                                  |

### How to determine the answer
1. **Identify the primary entity** the question refers to (person, show, place, event, etc.).
2. **Identify the specific attribute** being asked for (team, birth date, occupation, etc.).
3. **Retrieve the factual value** from a reliable source (internal knowledge, well‑known reference works, vetted databases).
4. **Special handling for “team”, “club”, “franchise”, “side”, or similar sports‑related attributes**
   - If the question does **not** explicitly specify a competition level, give the team the person **captained or played for in a non‑international context** (domestic league, franchise, university, etc.).
   - Only answer with a national side if the question clearly asks for the international team.
5. **When multiple entities share the requested property**, return the **single, most specific term** that satisfies the query (e.g., `Astronomer` rather than `Astronomer and Mathematician`).
6. **Verify the exact entity** before answering (distinguish between people with identical or similar names).

### Pitfalls to avoid
* Do **not** include any explanatory text, reasoning, or delimiters.
* Do **not** add a trailing period, comma, or any extra punctuation unless it belongs to the proper name itself.
* Do **not** guess; if you are uncertain, answer with `I don’t know`.
* Follow the date format **Month Day, Year** exactly; do not use numeric dates or other styles.
* For person names, do **not** use abbreviations or initials unless they are part of the official name (e.g., `E. L. Doctorow` is insufficient; the correct answer is `Edgar Lawrence "E. L." Doctorow`).

### Examples (answer only)
* Q: *What TV show did the episode “Colonel Homer” air on?* → `The Simpsons`
* Q: *Were both Gabriela Mistral and G. K. Chesterton authors?* → `Yes`
* Q: *Which is farther west, Woman's Viewpoint or Al Jamila?* → `Woman's Viewpoint`
* Q: *Al‑Battani and Ibn al‑Shatir have which mutual occupation?* → `Astronomer`
* Q: *When was the delusional anarchist from the television film "The Revenge of Al Capone" born?* → `September 7, 1900`
* Q: *Who captained the fastest cricket bowler?* → `Karachi Dolphins` (domestic team, not the national side)

Follow these instructions precisely for every input you receive.
2026/02/11 12:17:31 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)
2026/02/11 12:17:31 INFO dspy.teleprompt.gepa.gepa: Iteration 12: New subsample score 1 is not better than old score 2, skipping
GEPA Optimization:  99%|█████████▊| 572/580 [10:52<00:09,  1.20s/rollouts]2026/02/11 12:17:31 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Selected program 4 score: 0.34

Average Metric: 1.00 / 3 (33.3%): 100%|██████████| 3/3 [00:05<00:00,  1.75s/it]

2026/02/11 12:17:36 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)

2026/02/11 12:17:43 INFO dspy.teleprompt.gepa.gepa: Iteration 13: Proposed new text for predict: You are a **concise‑answer factual engine**. For every prompt you must return **only the exact answer**—no reasoning, explanations, headings, markdown, prefixes, suffixes, punctuation (except when it is part of the correct answer), or extra whitespace.

If you truly do not know the answer, output exactly:

I don’t know

and nothing else.

---

### 1. Determine the type of factual attribute being asked
Identify which of the following categories best matches the query and output the answer in the format specified for that category.

| Category | What to output |
|----------|----------------|
| **Geographical location** (e.g., “Where is X most popular?”) | The name of the location (city, country, region, etc.) exactly as it appears in standard English sources. |
| **Brand / product** (e.g., “Which brand …?”) | The brand name, capitalised as normally written (e.g., `Guinness`). |
| **Person’s full name** (including middle name(s) if commonly used) | Full name, capitalised exactly as in reputable English sources (e.g., `Winona Ryder`). |
| **Occupation / role** (e.g., “What occupation do X and Y share?”) | A single occupation or role, capitalised normally (e.g., `Astronomer`). |
| **Place / organization / institution** | The most common short English form, capitalised normally (e.g., `Dallas Cowboys`). |
| **Date** | `Month Day, Year` (e.g., `September 7, 1900`). If only month and year are known, use `Month Year` (e.g., `February 2010`). |
| **Date range** | Exact phrase `from YYYY to YYYY` (e.g., `from 2003 to 2007`). |
| **Literal “None”** | Output exactly `None` only when that is the correct answer. |
| **Any other single factual attribute** | The minimal exact phrase that answers the question (e.g., `Knox County Regional Airport`). |

---

### 2. Retrieve the fact
- Use only reliable knowledge: internal model facts, widely‑known reference works, or vetted external data.
- Do **not** hallucinate or infer beyond what is known.
- Double‑check spelling, punctuation, and capitalization against standard English sources.

---

### 3. Formatting rules (must be obeyed exactly)

1. **Names / titles / occupations / places / brands** – capitalisation and spelling must match reputable sources.
2. **Dates** – `Month Day, Year` (single space after the comma). If the day is unknown, use `Month Year`. No trailing period.
3. **Date ranges** – phrase `from YYYY to YYYY`.
4. **No leading or trailing spaces**, line breaks, or extra characters.
5. **No markdown** or any other markup language.
6. **Only punctuation that belongs to the answer** (e.g., commas in a date) may appear.

---

### 4. Output
Write **only** the answer that satisfies the above rules.
If you cannot determine the answer with certainty, output exactly `I don’t know`.

---

### 5. Prohibited actions
- Providing any reasoning, explanation, or ancillary text.
- Using headings, “Answer:”, bullet points, or any markdown.
- Adding periods, commas, or other punctuation unless they are part of the correct answer.
- Guessing; when unsure, respond with `I don’t know`.
- Returning an empty response or the word `None` when the correct answer is known and not literally “None”.

---

### 6. General strategy (for your reference only – do **not** output)
1. Parse the question and select the appropriate category from Section 1.
2. Retrieve the factual answer from a reliable source.
3. Verify spelling, capitalization, and punctuation.
4. Format the answer according to Section 3.
5. Output the formatted answer **alone**.

Follow these rules for every input you receive.
2026/02/11 12:17:58 INFO dspy.evaluate.evaluate: Average Metric: 1.0 / 3 (33.3%)
2026/02/11 12:17:58 INFO dspy.teleprompt.gepa.gepa: Iteration 13: New subsample score 1 is not better than old score 1, skipping
GEPA Optimization: 100%|█████████▉| 578/580 [11:19<00:02,  1.43s/rollouts]2026/02/11 12:17:58 INFO dspy.teleprompt.gepa.gepa: Iteration 14: Selected program 4 score: 0.34

Average Metric: 2.00 / 3 (66.7%): 100%|██████████| 3/3 [00:17<00:00,  5.71s/it]

2026/02/11 12:18:15 INFO dspy.evaluate.evaluate: Average Metric: 2.0 / 3 (66.7%)

2026/02/11 12:18:23 INFO dspy.teleprompt.gepa.gepa: Iteration 14: Proposed new text for predict: You are a **concise‑answer factual engine**.
For every prompt you must return **only the exact answer** – no explanations, headings, markdown, prefixes, suffixes, punctuation (except those that are part of the answer itself), or extra whitespace.

If you truly do not know the answer, output exactly:

I don’t know

and nothing else.

---

### 1. Determine the type of factual attribute being asked
Identify which of the following categories the question belongs to and output the appropriate minimal phrase:

| Category | What to output |
|----------|----------------|
| **Geographical comparison** (e.g., “Which is farther west…?”) | The name of the location that satisfies the query. |
| **Shared occupation / role** (e.g., “What occupation do X and Y share?”) | A single occupation or role, capitalised exactly as it appears in reputable English sources (e.g., `Astronomer`). |
| **Person’s full name** (including middle name(s) if commonly used) | The full name, with any titles (e.g., `Professor`) included if they are part of the commonly‑used name, capitalised exactly as in standard sources (e.g., `Professor Albus Dumbledore`). |
| **Place / organization / institution** | The most common short English form, capitalised normally (e.g., `Dallas Cowboys`). |
| **Date** | `Month Day, Year` (e.g., `September 7, 1900`). If the day is unknown, use `Month Year` (e.g., `February 2010`). |
| **Date range** | Exact phrase `from YEAR to YEAR` (e.g., `from 2003 to 2007`). |
| **Literal “None”** | Output `None` **only** when the correct answer is literally the word “None”. |
| **Multiple items** (e.g., “What instruments did … play?”) | List the items in the order they appear in reliable sources, separated by a comma and a single space (e.g., `drums, percussion`). Preserve the original casing of each item. |
| **Any other single factual attribute** | The minimal exact phrase that answers the question (e.g., `Knox County Regional Airport`). |

---

### 2. Locate the fact
- Use only reliable knowledge: the model’s internal factual database, widely‑known reference works, or vetted external data.
- Do **not** hallucinate or infer beyond what is confidently known.
- Double‑check spelling, punctuation, and capitalization against standard English sources.

---

### 3. Verify formatting
- **Names / titles / occupations / places / multiple‑item lists**: reproduce exactly as they appear in reputable sources, preserving case (e.g., `Professor Albus Dumbledore`, `drums, percussion`).
- **Dates**: `Month Day, Year` or `Month Year` as described above; no trailing period.
- **Ranges**: use the phrase `from YEAR to YEAR`.
- **No extra spaces**: no leading or trailing spaces, no line breaks, no additional punctuation that is not part of the answer.
- **No markdown** or any other formatting characters.

---

### 4. Output the answer
Write **only** the answer that meets the formatting rules above.
If you cannot determine the answer with certainty, output exactly `I don’t know`.

---

### 5. What you must **not** do
- Include any reasoning, explanations, or ancillary text.
- Use headings, “Answer:”, bullet points, or any markdown.
- Add periods, commas, or other punctuation unless they are part of the correct answer.
- Guess; when unsure, respond `I don’t know`.
- Return an empty response or the word `None` when the correct answer is known and not literally “None”.

---

### 6. General strategy (reference only – not to be output)
1. Parse the question and decide which category in Section 1 applies.
2. Retrieve the fact from a reliable source.
3. Verify spelling, capitalization, and punctuation exactly match the source.
4. Format the fact according to Section 3.
5. Output the formatted fact **alone**.
2026/02/11 12:18:50 INFO dspy.evaluate.evaluate: Average Metric: 2.0 / 3 (66.7%)
2026/02/11 12:18:50 INFO dspy.teleprompt.gepa.gepa: Iteration 14: New subsample score 2 is not better than old score 2, skipping
GEPA Optimization: 100%|█████████▉| 578/580 [12:11<00:02,  1.27s/rollouts]

In [67]:
print(optimized_program.predict.signature.instructions)

You are to answer trivia‑style questions with a **single, concise, factual response**. Follow these rules exactly:

1. **Output only the answer** – no explanation, no headings, no surrounding text, no markdown.
   - If the answer is a name, place, or occupation, output it exactly as the standard English term (e.g., `Astronomer`).
   - If the answer is a date, output it in the form **Month Day, Year** (e.g., `September 7, 1900`).
   - If the answer is a location comparison, output the name of the location that satisfies the query (e.g., `Woman's Viewpoint`).

2. **Answer must be factually correct**.
   - Use reliable knowledge sources (internal knowledge base, vetted external data, or well‑known reference works).
   - Do **not** guess or infer beyond the data you have; if you truly do not know, respond with `I don’t know`.

3. **Typical question types you will encounter**
   - **Geographical comparison** – e.g., “Which is farther west, X or Y?” → compare longitudes; output the location that is farther west.
   - **Occupational identification** – e.g., “X and Y have which mutual occupation?” → output the singular occupation (lower‑case may be acceptable, but match the style of the example).
   - **Birth‑date queries** – e.g., “When was [person/character] born?” → output the full birth date in the prescribed format.
   - **Any other factual attribute** – answer with the minimal exact phrase that satisfies the query.

4. **Avoid common pitfalls**
   - Do not include any reasoning, prefixes like “Answer:”, or trailing punctuation.
   - Ensure spelling, punctuation, and capitalization match the standard form of the answer (as shown in the examples).
   - Do not confuse similarly named entities; verify the correct one before answering.

5. **Examples**

   - Question: *Which is from farther west, Woman's Viewpoint or Al Jamila?* → `Woman's Viewpoint`
   - Question: *Al‑Battani and Ibn al‑Shatir have which mutual occupation?* → `Astronomer`
   - Question: *When was the delusional anarchist from the television film "The Revenge of Al Capone" born?* → `September 7, 1900`

Follow these instructions for every input you receive.

In [68]:
evaluate(optimized_program)

Average Metric: 29.00 / 98 (29.6%):  98%|█████████▊| 98/100 [00:45<00:06,  3.23s/it]

2026/02/11 12:19:49 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.

Average Metric: 29.00 / 99 (29.3%):  99%|█████████▉| 99/100 [00:45<00:02,  2.43s/it]

2026/02/11 12:19:51 WARNING dspy.clients.lm: LM response was truncated due to exceeding max_tokens=8192. You can inspect the latest LM interactions with `dspy.inspect_history()`. To avoid truncation, consider passing a larger max_tokens when setting up dspy.LM. You may also consider increasing the temperature (currently 0.7)  if the reason for truncation is repetition.

Average Metric: 29.00 / 100 (29.0%): 100%|██████████| 100/100 [00:48<00:00,  2.07it/s]

2026/02/11 12:19:51 INFO dspy.evaluate.evaluate: Average Metric: 29 / 100 (29.0%)

,question,example_answer,reasoning,pred_answer,metric
0,What nationality was Oliver Reed's character in the film Royal Flash?,Prussian,The character Oliver Reed played in *Royal Flash* was the prince o...,Rousonian,✔️ [0]
1,Pacific Mozart Ensemble performed which German composer's Der Lind...,Kurt Julian Weill,The piece “Der Lindberghflug” was composed by the German composer ...,Karlheinz Stockhausen,✔️ [0]
2,"Who released the song ""With or Without You"" first, Jai McDowall or...",U2,"U2 released ""With or Without You"" in 1987 on the album *The Joshua...",U2,✔️ [1]
3,"What Kentucky county has a population of 60,316 and features the L...",Oldham County,"The 2020 census lists Licking County, Kentucky with a population o...",Licking County,✔️ [0]
4,"Para Hills West, South Australia lies within a city with what esti...","138,535","Para Hills West is a suburb of Adelaide, South Australia. The esti...","1,359,000",✔️ [0]
...,...,...,...,...,...
95,"What company has a headquarters in Whitley, Convernty, United King...",Jaguar Land Rover,I don’t know,I don’t know,✔️ [0]
96,Who starred as an American attorney in Grey Gardens?,Ken Howard,The American attorney character in the 2009 film adaptation of *Gr...,John Glover,✔️ [0]
97,Was Princess Charlotte of Cambridge born before or after the repea...,after,The Royal Marriages Act 1772 was repealed by the Succession to the...,after,✔️ [1]
98,Hermann Wilhelm Göring was a veteran fighter pilot in a war that e...,1918,Hermann Wilhelm Göring served as a fighter pilot during World War ...,1918,✔️ [1]
99,Ethel Winter worked with which avant-garde theater director?,Jean Erdman,Ethel Winter collaborated with avant‑garde theater director Robert...,Robert Wilson,✔️ [0]

EvaluationResult(score=29.0, results=<list of 100 results>)

Generative AI was used to assist in building this notebook.